[general]
restore_cursor_position = true

[hotkeys]
"Ctrl+F" = "grid"
"Ctrl+S" = "scroll"

[hints]
enabled = false

[grid]
font_family = "JetBrainsMonoNLNFP-ExtraBold"

characters = "aoeuidhtnspyfgcrlqjkxbmwvz"
sublayer_keys = "gcrhtnmwv"

[action]
[action.key_bindings]
left_click = "Shift+H"
middle_click = "Shift+T"
right_click = "Shift+N"
mouse_down = "Shift+R"
mouse_up = "Shift+C"

[smooth_cursor]
move_mouse_enabled = true
steps = 10
delay = 1

[metrics]
enabled = false

[logging]
log_level = "info"
disable_file_logging = true
